# action名称
name: Publish and Release

# 代码合并到main分支时触发
on:
  push:
    branches: [main]

# 任务
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'publish')

    steps:
      - name: 检查main分支
        uses: actions/checkout@main

      - name: 设置node版本
        uses: actions/setup-node@main
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org
      
      - name: 安装依赖
        run: npm install

      - name: build
        run: npm run build

      - name: 发布到npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
      - name: publish 成功通知
        run: echo npm 推送成功

      - name: 读取当前版本号
        id: create_release
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.value }}
          release_name: v${{ steps.version.outputs.value }}
          draft: false
          prerelease: false